<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="1524589-200.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="1524589-200.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Sounds\breaktime.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Sounds\studytime.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist &quot;$(TargetDir)Study Music&quot; (mkdir &quot;$(TargetDir)Study Music&quot;)&#xD;&#xA;if not exist &quot;$(TargetDir)Break Music&quot; (mkdir &quot;$(TargetDir)Break Music&quot;)&#xD;&#xA;if not exist &quot;$(TargetDir)Long Break Music&quot; (mkdir &quot;$(TargetDir)Long Break Music&quot;)" />
  </Target>

</Project>
